[package]
name = "pfo_derive"
version.workspace = true
license.workspace = true
authors.workspace = true
edition.workspace = true

[lib]
proc-macro = true

[dependencies]
heck = "0.5.0"
quote = "1.0.41"
proc-macro2 = "1.0.101"
syn = "2.0.106"
